from .templates import *
from .templates_attendance import *

__all__ = [
    "ALL_PAIRS_TEMPLATE",
    "NO_PAIRS_TEMPLATE",
    "NO_LESSONS_TODAY_TEMPLATE",
    "CHOOSE_PAIR_TEMPLATE",
    "POLL_TEMPLATE",
    "WHICH_PAIR_TEMPLATE",
    "attendance_for_headmen_template",
    "start_message_template",
    "CHOOSE_STUDENT_ROLE_TEMPLATE",
    "REGISTRATION_DENIED_TEMPLATE",
    "REGISTRATION_ACCEPTED_TEMPLATE",
    "YOU_WERE_DENIED_TEMPLATE",
    "YOU_WERE_ACCEPTED_TEMPLATE",
    "ASK_UNIVERSITY_TEMPLATE",
    "successful_role_choose_template",
    "successful_university_choose_template",
    "asking_fullname_validation_template",
    "ASK_GROUP_TEMPLATE",
    "INCORRECT_UNIVERSITY_TEMPLATE",
    "INCORRECT_STUDENT_ROLE_TEMPLATE",
    "GROUP_DOESNT_EXISTS_TEMPLATE",
    "ASK_NAME_TEMPLATE",
    "ASK_SURNAME_TEMPLATE",
    "YOUR_APPLY_WAS_SENT_TO_ADMINS_TEMPLATE",
    "YOUR_APPLY_WAS_SENT_TO_HEADMAN_TEMPLATE",
    "YOU_CAN_NOT_ANSWER_TIME_TEMPLATE",
    "YOU_CAN_NOT_ANSWER_DAY_TEMPLATE",
    "HEADMAN_ALREADY_EXISTS_TEMPLATE",
    "FAQ_TEMPLATE",
    "GROUP_DOESNT_REGISTERED_TEMPLATE",
    "BIRTHDATE_INCORRECT_TEMPLATE",
    "ASK_BIRTHDATE_TEMPLATE",
    "TOO_MUCH_NAME_LENGTH_TEMPLATE",
    "TOO_MUCH_SURNAME_LENGTH_TEMPLATE",
    "profile_info",
    "ASK_NEW_NAME_TEMPLATE",
    "ASK_NEW_SURNAME_TEMPLATE",
    "asking_name_validation_template",
    "asking_surname_validation_template",
    "your_choice_is_template",
    "WHAT_DO_YOU_WANNA_EDIT_TEMPLATE"
]
